#!/bin/bash
echo "🚂 Sovereign Self - Railway Setup"
echo ""
echo "Run these commands ONE AT A TIME:"
echo ""
echo "1. Link Railway project:"
echo "   railway link"
echo ""
echo "2. Set up database:"
echo "   railway run \"cd apps/api && npx prisma db push --accept-data-loss\""
echo ""
echo "3. Get Railway URL:"
echo "   railway domain"
echo ""
echo "4. Configure Vercel (cd to apps/web first):"
echo "   cd apps/web"
echo "   vercel env add VITE_API_URL production"
echo "   # Enter your Railway URL/api"
echo "   vercel --prod"
echo ""
echo "5. Update Railway CORS:"
echo "   cd .."
echo "   railway variables set CORS_ORIGIN=\"https://your-vercel-url.vercel.app\""
echo ""
echo "✅ Done!"
